### ISSUE TITLE
Scroll to hash on URL link click

### ISSUE THREAD

**Issue by aubreythreadgill** [ncoughlin/scroll-to-hash-element#1]
Thanks for building and sharing this component, Nick!

I've implemented it, but when I click a link to mysite.com/#section, the site doesn't take me to the `<div id="section">Section</div>`. Do you have any thoughts on what I may be doing wrong?

I noticed your personal site works well (and ironically so does reactrouter.com). For example, clicking a link to https://ncoughlin.com/posts/react-router-v6-hash-links/#installation would take me to the `<h2 id="installation">'Installation'</h2>` section.

**Comment by ncoughlin** [comment]
I'd be happy to help you troubleshoot this if you could provide some more information.
If you could provide the following that would be helpful
1. result of `console.log(location)` inside the ScrollToHashElement component
2. an example of how you have typed your link
3. example of where you inserted the ScrollToHashElement component in your application

**Comment by aubreythreadgill** [comment]
1. `console.log(location)`: Object hash: "#contact" key: "default" pathname: "/" search: "" state: null [[Prototype]]: Object //
2. Link(s): http://localhost:3000/#contact (also tried production link https://aubbrey.com/#contact). Click: I experimented with pasting in Slack and Word, then clicking the link. This did work for your site.
Note: If I load the page `http://localhost:3000`, then `Ctrl+L` into the URL bar, then type `/#contact` at the end, it works.
3. I've inserted `<ScrollToHashElement />` as the first item inside of `<div className="App">`. I also tried moving it further down inside of `<div className="body">`.

I greatly appreciate the help troubleshooting! Being able to share a link directly to the contact section of my single-page site will be a huge help.

**Comment by aubreythreadgill** [comment]
I added a few more logs. The values of `location` and `hash` return `contact`, however `element` returns null. Going to continue digging into this.

**Comment by ncoughlin** [comment]
Interesting. It is working for me on the production link actually. There is an interesting behaviour where if I click the hashlink from outside the page it waits until the element loads, and then jumps to it. If I am already on your site loaded it jumps to it immediately. I think what is going on is that the contact section is on the bottom of the page and is being rendered last, so when the page first loads the element to scroll to is null until it renders.

**Comment by aubreythreadgill** [comment]
Got it. There are a few heavy iframes above it, so I could see how that might be the case. I may add a `setTimeout` to the `scrollIntoView`. Or adding a ternary with a Loader to the iframes may allow it to procced to rendering the Contact section more quickly.

Thanks again for the help on this!

**Comment by rondog** [comment]
I'm having this same issue. @aubreythreadgill did you end up doing a timeout? I cant seem to get mine working. Problem only happens when coming from a different page.
