### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by darren-finch** [ncoughlin/scroll-to-hash-element#2]
Hello!

I am looking to use this component in one of my projects and would like a license to be added to this component to make sure the author of the repo is okay with that.

Regards,
Darren

**Comment by ncoughlin** [comment]
Darren,I can add that on Monday, but I’m the author and I give you full permission to fork or use however you want. No restrictions. NickSent from my iPhoneOn Apr 22, 2023, at 5:25 AM, Darren Finch ***@***.***> wrote:﻿
Hello!
I am looking to use this component in one of my projects and would like a license to be added to this component to make sure the author of the repo is okay with that.
Regards,
Darren

**Comment by darren-finch** [comment]
Thank you Nick!
