### ISSUE TITLE
Enhancements to scroll to hash

### ISSUE THREAD

**Issue by akshayshippy** [ncoughlin/scroll-to-hash-element#4]
Use below code to support scroll to hash when current page/route is different from where the hash is located. It also ensures scroll to hash is only run once the component is rendered using useLayoutEffect() (edge cases where document.getElementById() errors out because page has not rendered yet).

Use below code to fix 
```
import { useLayoutEffect } from 'react';
import { useLocation } from 'react-router-dom';

const ScrollToHashElement = () => {
    const location = useLocation();

    useLayoutEffect(() => {
        const { hash } = location;

        const removeHashCharacter = (str) => {
            const result = str.slice(1);
            return result;
        };

        if (hash) {
            const element = document.getElementById(removeHashCharacter(hash));

            if (element) {
                element.scrollIntoView({
                    behavior: 'smooth',
                    inline: 'nearest',
                });
            }
        }
    }, [location]);

    return null;
};

export default ScrollToHashElement;
```

**Comment by camsmy** [comment]
I just wanted to say a big thank you! I was struggling with document.getElementById() giving me null, and your solution using useLayoutEffect solved it for me. I made a few adjustments to adapt it to my project, and now it's working perfectly. Thanks a bunch! Have an amazing day!

**Comment by akshayshippy** [comment]
closing this and creating a PR with new account
