### ISSUE TITLE
Contribution & features

### ISSUE THREAD

**Issue by urieltfk** [ncoughlin/scroll-to-hash-element#5]
I think adding optional parameters to control the scroll behaviour would be nice.
In addition, this functionality is useful both as a hook & as a component.
So maybe this library should give the option to import both? 

Is this package open for contributions?
And of course, Thank you :)

**Comment by ncoughlin** [comment]
Yes definitely open to contributions. I would love that. Go ahead and send a pull request. Please test thoroughly beforehand as my time to vet your changes will be limited.

Thanks.
